name: WAIVO Rule Sync

on:
  push:
    paths:
      - 'new-rule.yaml'

jobs:
  append-rule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Append new rule to falco-sync-rules.yaml
        run: |
          echo "" >> falco-sync-rules.yaml
          cat new-rule.yaml >> falco-sync-rules.yaml

      - name: Clear the staging rule
        run: |
          echo "# Cleared after sync" > new-rule.yaml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Append Falco rule from WAIVO"
          branch: main
